create table oxal1.tbl_int_fagll03(
    id uniqueidentifier not null constraint tbl_int_fagll03_df1 default newsequentialid(),
    kokrs char(4) not null,
    bukrs char(4) not null,
    prctr char(10) not null,
    rldnr char(2) not null,
    u_ldgrp char(2),
    gjahr smallint,
    monat tinyint,
    kostl char(10),
    aufnr varchar(10),
    projk varchar(35),
    vbund varchar(5),
    glvor char(4) not null,
    u_tcode varchar(10),
    blart char(2) not null,
    shkzg char(1) not null,
    konto char(10) not null,
    u_lokkt char(10),
    sgtxt nvarchar(1000),
    u_bktxt nvarchar(1000),
    belnr char(10) not null,
    buzei smallint,
    werks char(4),
    u_ebeln char(10),
    ebelp smallint,
    u_matnr char(10),
    gbeextwg_ebx varchar(20),
    gkart char(1) not null,
    gkont varchar(10) not null,
    u_lifnr char(7),
    dmshb decimal(12, 2) not null,
    hwaer char(3) not null,
    wrshb decimal(12, 2) not null,
    waers char(3) not null,
    menge decimal(11, 4),
    u_usnam varchar(20) not null,
    valut date,
    budat date not null,
    bldat date not null,
    u_cpudt date not null,
    load_file varchar(100),
    load_uuid uniqueidentifier,
    mod_de varchar(20) not null,
    mod_timp datetime not null constraint tbl_int_fagll03_df2 default current_timestamp,
    constraint tbl_int_fagll03_pk primary key (id),
    constraint tbl_int_fagll03_fk1 foreign key (kokrs, bukrs) references oxal1.tbl_int_cocode(coarea, cod),
    constraint tbl_int_fagll03_uq1 unique (bukrs, gjahr, belnr, buzei),
    constraint tbl_int_fagll0_ck1 check (gjahr between 2000 and 9999),
    constraint tbl_int_fagll0_ck2 check (monat between 1 and 16),
    constraint tbl_int_fagll0_ck3 check (buzei >= 0)
);
go

create index tbl_int_fagll03_ix1 on oxal1.tbl_int_fagll03(gjahr asc, monat asc, kokrs asc);
go

create index tbl_int_fagll03_ix2 on oxal1.tbl_int_fagll03(kokrs asc, load_uuid asc);
go