create table oxal1.tbl_int_kob1(
    id uniqueidentifier not null constraint tbl_int_kob1_df1 default newsequentialid(),
    kokrs char(4) not null,
    bukrs char(4) not null,
    gjahr smallint not null,
    perio tinyint not null,
    obart char(3) not null,
    aufnr varchar(10) not null,
    obj_txt nvarchar(100),
    vbund varchar(5),
    pobart char(3),
    pobid varchar(35),
    pob_txt nvarchar(100),
    objnr_n1 varchar(35),
    vrgng char(4) not null,
    orgvg char(4),
    logsystem char(10),
    blart char(2),
    beknz char(1) not null,
    kstar char(10) not null,
    cel_ktxt nvarchar(100),
    sgtxt nvarchar(100),
    bltxt nvarchar(100),
    belnr char(10) not null,
    buzei smallint not null,
    zzco_belnr char(10),
    refbz_fi smallint,
    werks char(4),
    ebeln char(10),
    ebelp smallint,
    ebtxt nvarchar(100),
    matnr char(10),
    mat_txt nvarchar(100),
    gbeextwg_ebx varchar(20),
    refbt char(1),
    refgj smallint,
    refbn varchar(10),
    stokz char(1),
    awref_rev varchar(10),
    gkoar char(1),
    gkont varchar(10),
    gkont_ktxt nvarchar(100),
    zz_lif nvarchar(100),
    wrgbtr decimal(12, 2) not null,
    kwaer char(3) not null,
    wtgbtr decimal(12, 2) not null,
    twaer char(3) not null,
    mbgbtr decimal(11, 4),
    meinb char(5),
    usnam varchar(20) not null,
    wsdat date,
    budat date not null,
    bldat date not null,
    cpudt date not null,
    load_file varchar(100),
    load_uuid uniqueidentifier,
    mod_de varchar(20) not null,
    mod_timp datetime not null constraint tbl_int_kob1_df2 default current_timestamp,
    constraint tbl_int_kob1_pk primary key (id),
    constraint tbl_int_kob1_fk1 foreign key (kokrs, bukrs) references oxal1.tbl_int_cocode(coarea, cod),
    constraint tbl_int_kob1_uq1 unique (bukrs, gjahr, perio, belnr, buzei),
    constraint tbl_int_kob1_ck1 check (gjahr between 2000 and 9999),
    constraint tbl_int_kob1_ck2 check (perio between 1 and 16),
    constraint tbl_int_kob1_ck3 check (buzei >= 0)
);
go

create index tbl_int_kob1_ix1 on oxal1.tbl_int_kob1(gjahr asc, perio asc, kokrs asc);
go

create index tbl_int_kob1_ix2 on oxal1.tbl_int_kob1(kokrs asc, load_uuid asc);
go